name: hits_and_blows_game
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  pinput: ^5.0.1

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.5
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon.png
    - assets/images/icon_no_background.png
    - assets/images/icon_min.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont.ttf
        - asset: assets/fonts/Roboto-VariableFont.ttf
          style: italic